service: url-shortener

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x

functions:
  main:
    handler: main/index.handler
    events:
      - http:
          path: /
          method: get
  create:
    handler: create/index.handler
    events:
      - http:
          path: /
          method: post
  redirect:
    handler: redirect/index.handler
    events:
      - http:
          path: /{slug}
          method: get
    environment:
      URL_INSTALL: http://install
      USL_TEST: http://test

